server:
  port: 8081

spring:
  application:
    name: redis
  data:
    redis:
      #host: 127.0.0.1
      #port: 6379
      cluster:
        #nodes: 127.0.0.1:7001, 127.0.0.1:7002, 127.0.0.1:7003, 127.0.0.1:7004, 127.0.0.1:7005, 127.0.0.1:7006
        nodes: localhost:7001, localhost:7002, localhost:7003, localhost:7004, localhost:7005, localhost:7006
        max-redirects: 3
        password: bitnami
        timeout: 500ms
  cache:
    type: redis
  session:
    redis:
      flush-mode: on_save
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
        show_sql: true
